// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylbdmqumhlqckgpsdzvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsYmRtcXVtaGxxY2tncHNkenZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MTM3MzYsImV4cCI6MjA1Njk4OTczNn0.p-LFsMtEU0NHnT735_8P5ecTIDKXsm-Yuj0tR4wombQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);